// This file was auto-generated by prisma-generator-typescript-interfaces

export interface AppConfig {
  id: string;
  value: string;
}

export interface User {
  id: number;
  name: string;
  email: string;
  password: string;
  createdAt: Date;
  createdBy: string | null;
  updatedAt: Date | null;
  updatedBy: string | null;
  roleId: number;
  role?: RolePermissions;
}

export interface RolePermissions {
  id: number;
  name: string;
  accessUsers: number;
  accessPermissions: number;
  users?: User[];
}
