// This file was auto-generated by prisma-generator-typescript-interfaces

export interface User {
  id: number;
  name: string;
  email: string;
  password: string;
  createdAt: Date;
  createdBy: number;
  updatedAt: Date | null;
  updatedBy: number;
  roleId: number;
  role?: RolePermissions;
}

export interface RolePermissions {
  id: number;
  name: string;
  userAccounts: number;
  rolePermissions: number;
  customers: number;
  users?: User[];
}
